const en = {
  'schedule.regular': 'Regular weekly schedule',
  'schedule.editRegular': 'Edit regular schedule',
  'schedule.saveRegular': 'Save regular schedule',
  'schedule.regularSaved': 'Regular schedule saved.',
  'schedule.working': 'Working',
  'schedule.off': 'Off',
  'schedule.useLocationHours': 'Use location hours',
  'schedule.locationHoursUnavailable': 'No opening hours are configured for this location and day.',
  'schedule.generatorMode': 'Schedule source',
  'schedule.useRegular': 'Use regular schedule',
  'schedule.customDays': 'Set days manually',
  'schedule.preview': 'Shift preview',
  'schedule.previewDescription': 'Review every shift before creation. Conflicts are skipped.',
  'schedule.ready': 'Ready',
  'schedule.duplicate': 'Duplicate',
  'schedule.overlap': 'Overlap',
  'schedule.invalid': 'Invalid time',
  'schedule.noReady': 'There are no valid shifts to create.',
  'schedule.conflictsSkipped': '{count} conflicting or invalid shifts were skipped.',
  'schedule.selectReady': 'Include valid shift on {date}',
  'schedule.recheckConflict': 'The schedule changed while you were reviewing it. Review the updated conflicts.',
  'schedule.concurrentOverlap': 'This shift overlaps another shift for the same employee. Refresh the schedule and review the conflict.',
  'schedule.print': 'Print schedule',
  'schedule.printTitle': 'Employee schedule',
  'schedule.printEmployees': 'Employees to print',
  'schedule.printAll': 'Select all employees in this period',
  'schedule.printRequired': 'Select at least one employee with shifts.',
  'schedule.period': 'Schedule period',
  'schedule.day': 'Day',
  'schedule.break': 'Break',
  'schedule.duration': 'Working duration',
  'schedule.weeklyTotal': 'Total hours',
  'schedule.personalNumber': 'Employee number',
  'schedule.noShiftsToPrint': 'No shifts are available for the selected employees and period.',
} as const

type ScheduleDictionary = Record<keyof typeof en, string>

export const employeeScheduleDictionaries: Record<'en' | 'de' | 'ru' | 'tr' | 'uk' | 'pl' | 'fr', ScheduleDictionary> = {
  en,
  de: {
    'schedule.regular': 'Regelmäßiger Wochenplan', 'schedule.editRegular': 'Wochenplan bearbeiten', 'schedule.saveRegular': 'Wochenplan speichern', 'schedule.regularSaved': 'Wochenplan gespeichert.', 'schedule.working': 'Arbeitstag', 'schedule.off': 'Frei', 'schedule.useLocationHours': 'Öffnungszeiten übernehmen', 'schedule.locationHoursUnavailable': 'Für diesen Standort und Tag sind keine Öffnungszeiten hinterlegt.', 'schedule.generatorMode': 'Planquelle', 'schedule.useRegular': 'Regelmäßigen Plan verwenden', 'schedule.customDays': 'Tage manuell festlegen', 'schedule.preview': 'Schichtvorschau', 'schedule.previewDescription': 'Prüfe jede Schicht vor dem Erstellen. Konflikte werden übersprungen.', 'schedule.ready': 'Bereit', 'schedule.duplicate': 'Duplikat', 'schedule.overlap': 'Überschneidung', 'schedule.invalid': 'Ungültige Zeit', 'schedule.noReady': 'Es gibt keine gültigen Schichten zum Erstellen.', 'schedule.conflictsSkipped': '{count} konflikthafte oder ungültige Schichten wurden übersprungen.', 'schedule.selectReady': 'Gültige Schicht am {date} einbeziehen', 'schedule.recheckConflict': 'Der Plan wurde während der Prüfung geändert. Prüfe die aktualisierten Konflikte.', 'schedule.concurrentOverlap': 'Diese Schicht überschneidet sich mit einer anderen Schicht desselben Mitarbeiters. Aktualisieren Sie den Dienstplan und prüfen Sie den Konflikt.', 'schedule.print': 'Dienstplan drucken', 'schedule.printTitle': 'Mitarbeiter-Dienstplan', 'schedule.printEmployees': 'Mitarbeiter für den Druck', 'schedule.printAll': 'Alle Mitarbeiter in diesem Zeitraum auswählen', 'schedule.printRequired': 'Wähle mindestens einen Mitarbeiter mit Schichten aus.', 'schedule.period': 'Planungszeitraum', 'schedule.day': 'Tag', 'schedule.break': 'Pause', 'schedule.duration': 'Arbeitszeit', 'schedule.weeklyTotal': 'Gesamtstunden', 'schedule.personalNumber': 'Personalnummer', 'schedule.noShiftsToPrint': 'Für die ausgewählten Mitarbeiter und den Zeitraum sind keine Schichten vorhanden.',
  },
  ru: {
    'schedule.regular': 'Регулярный недельный график', 'schedule.editRegular': 'Изменить недельный график', 'schedule.saveRegular': 'Сохранить недельный график', 'schedule.regularSaved': 'Недельный график сохранен.', 'schedule.working': 'Рабочий', 'schedule.off': 'Выходной', 'schedule.useLocationHours': 'Взять часы локации', 'schedule.locationHoursUnavailable': 'Для этой локации и дня часы работы не заданы.', 'schedule.generatorMode': 'Источник графика', 'schedule.useRegular': 'Использовать регулярный график', 'schedule.customDays': 'Настроить дни вручную', 'schedule.preview': 'Предпросмотр смен', 'schedule.previewDescription': 'Проверьте каждую смену до создания. Конфликты будут пропущены.', 'schedule.ready': 'Готово', 'schedule.duplicate': 'Дубликат', 'schedule.overlap': 'Пересечение', 'schedule.invalid': 'Некорректное время', 'schedule.noReady': 'Нет корректных смен для создания.', 'schedule.conflictsSkipped': 'Пропущено конфликтных или некорректных смен: {count}.', 'schedule.selectReady': 'Добавить корректную смену на {date}', 'schedule.recheckConflict': 'Во время проверки график изменился. Проверьте обновленные конфликты.', 'schedule.concurrentOverlap': 'Эта смена пересекается с другой сменой того же сотрудника. Обновите график и проверьте конфликт.', 'schedule.print': 'Печать графика', 'schedule.printTitle': 'График сотрудников', 'schedule.printEmployees': 'Сотрудники для печати', 'schedule.printAll': 'Выбрать всех сотрудников за период', 'schedule.printRequired': 'Выберите хотя бы одного сотрудника со сменами.', 'schedule.period': 'Период графика', 'schedule.day': 'День', 'schedule.break': 'Перерыв', 'schedule.duration': 'Рабочее время', 'schedule.weeklyTotal': 'Всего часов', 'schedule.personalNumber': 'Табельный номер', 'schedule.noShiftsToPrint': 'У выбранных сотрудников нет смен за этот период.',
  },
  tr: {
    'schedule.regular': 'Düzenli haftalık program', 'schedule.editRegular': 'Haftalık programı düzenle', 'schedule.saveRegular': 'Haftalık programı kaydet', 'schedule.regularSaved': 'Haftalık program kaydedildi.', 'schedule.working': 'Çalışıyor', 'schedule.off': 'İzinli', 'schedule.useLocationHours': 'Konum saatlerini kullan', 'schedule.locationHoursUnavailable': 'Bu konum ve gün için çalışma saati ayarlanmamış.', 'schedule.generatorMode': 'Program kaynağı', 'schedule.useRegular': 'Düzenli programı kullan', 'schedule.customDays': 'Günleri elle ayarla', 'schedule.preview': 'Vardiya önizlemesi', 'schedule.previewDescription': 'Oluşturmadan önce her vardiyayı inceleyin. Çakışmalar atlanır.', 'schedule.ready': 'Hazır', 'schedule.duplicate': 'Tekrar', 'schedule.overlap': 'Çakışma', 'schedule.invalid': 'Geçersiz saat', 'schedule.noReady': 'Oluşturulacak geçerli vardiya yok.', 'schedule.conflictsSkipped': '{count} çakışan veya geçersiz vardiya atlandı.', 'schedule.selectReady': '{date} tarihindeki geçerli vardiyayı dahil et', 'schedule.recheckConflict': 'İnceleme sırasında program değişti. Güncel çakışmaları inceleyin.', 'schedule.concurrentOverlap': 'Bu vardiya aynı çalışan için başka bir vardiyayla çakışıyor. Programı yenileyip çakışmayı inceleyin.', 'schedule.print': 'Programı yazdır', 'schedule.printTitle': 'Çalışan programı', 'schedule.printEmployees': 'Yazdırılacak çalışanlar', 'schedule.printAll': 'Bu dönemdeki tüm çalışanları seç', 'schedule.printRequired': 'Vardiyası olan en az bir çalışan seçin.', 'schedule.period': 'Program dönemi', 'schedule.day': 'Gün', 'schedule.break': 'Mola', 'schedule.duration': 'Çalışma süresi', 'schedule.weeklyTotal': 'Toplam saat', 'schedule.personalNumber': 'Personel numarası', 'schedule.noShiftsToPrint': 'Seçilen çalışanlar ve dönem için vardiya yok.',
  },
  uk: {
    'schedule.regular': 'Регулярний тижневий графік', 'schedule.editRegular': 'Редагувати тижневий графік', 'schedule.saveRegular': 'Зберегти тижневий графік', 'schedule.regularSaved': 'Тижневий графік збережено.', 'schedule.working': 'Робочий', 'schedule.off': 'Вихідний', 'schedule.useLocationHours': 'Використати години локації', 'schedule.locationHoursUnavailable': 'Для цієї локації та дня години роботи не налаштовані.', 'schedule.generatorMode': 'Джерело графіка', 'schedule.useRegular': 'Використати регулярний графік', 'schedule.customDays': 'Налаштувати дні вручну', 'schedule.preview': 'Попередній перегляд змін', 'schedule.previewDescription': 'Перевірте кожну зміну перед створенням. Конфлікти буде пропущено.', 'schedule.ready': 'Готово', 'schedule.duplicate': 'Дублікат', 'schedule.overlap': 'Перетин', 'schedule.invalid': 'Некоректний час', 'schedule.noReady': 'Немає коректних змін для створення.', 'schedule.conflictsSkipped': 'Пропущено конфліктних або некоректних змін: {count}.', 'schedule.selectReady': 'Додати коректну зміну на {date}', 'schedule.recheckConflict': 'Під час перевірки графік змінився. Перевірте оновлені конфлікти.', 'schedule.concurrentOverlap': 'Ця зміна перетинається з іншою зміною того самого працівника. Оновіть графік і перевірте конфлікт.', 'schedule.print': 'Друк графіка', 'schedule.printTitle': 'Графік працівників', 'schedule.printEmployees': 'Працівники для друку', 'schedule.printAll': 'Вибрати всіх працівників за період', 'schedule.printRequired': 'Виберіть хоча б одного працівника зі змінами.', 'schedule.period': 'Період графіка', 'schedule.day': 'День', 'schedule.break': 'Перерва', 'schedule.duration': 'Робочий час', 'schedule.weeklyTotal': 'Усього годин', 'schedule.personalNumber': 'Табельний номер', 'schedule.noShiftsToPrint': 'У вибраних працівників немає змін за цей період.',
  },
  pl: {
    'schedule.regular': 'Regularny harmonogram tygodniowy', 'schedule.editRegular': 'Edytuj harmonogram tygodniowy', 'schedule.saveRegular': 'Zapisz harmonogram tygodniowy', 'schedule.regularSaved': 'Harmonogram tygodniowy zapisany.', 'schedule.working': 'Praca', 'schedule.off': 'Wolne', 'schedule.useLocationHours': 'Użyj godzin lokalizacji', 'schedule.locationHoursUnavailable': 'Dla tej lokalizacji i dnia nie ustawiono godzin.', 'schedule.generatorMode': 'Źródło harmonogramu', 'schedule.useRegular': 'Użyj regularnego harmonogramu', 'schedule.customDays': 'Ustaw dni ręcznie', 'schedule.preview': 'Podgląd zmian', 'schedule.previewDescription': 'Sprawdź każdą zmianę przed utworzeniem. Konflikty zostaną pominięte.', 'schedule.ready': 'Gotowe', 'schedule.duplicate': 'Duplikat', 'schedule.overlap': 'Nakładanie', 'schedule.invalid': 'Nieprawidłowy czas', 'schedule.noReady': 'Brak prawidłowych zmian do utworzenia.', 'schedule.conflictsSkipped': 'Pominięto konfliktowe lub nieprawidłowe zmiany: {count}.', 'schedule.selectReady': 'Uwzględnij prawidłową zmianę {date}', 'schedule.recheckConflict': 'Harmonogram zmienił się podczas przeglądu. Sprawdź zaktualizowane konflikty.', 'schedule.concurrentOverlap': 'Ta zmiana nakłada się na inną zmianę tego samego pracownika. Odśwież harmonogram i sprawdź konflikt.', 'schedule.print': 'Drukuj harmonogram', 'schedule.printTitle': 'Harmonogram pracowników', 'schedule.printEmployees': 'Pracownicy do wydruku', 'schedule.printAll': 'Wybierz wszystkich pracowników w tym okresie', 'schedule.printRequired': 'Wybierz co najmniej jednego pracownika ze zmianami.', 'schedule.period': 'Okres harmonogramu', 'schedule.day': 'Dzień', 'schedule.break': 'Przerwa', 'schedule.duration': 'Czas pracy', 'schedule.weeklyTotal': 'Łącznie godzin', 'schedule.personalNumber': 'Numer pracownika', 'schedule.noShiftsToPrint': 'Brak zmian dla wybranych pracowników i okresu.',
  },
  fr: {
    'schedule.regular': 'Planning hebdomadaire régulier', 'schedule.editRegular': 'Modifier le planning hebdomadaire', 'schedule.saveRegular': 'Enregistrer le planning hebdomadaire', 'schedule.regularSaved': 'Planning hebdomadaire enregistré.', 'schedule.working': 'Travail', 'schedule.off': 'Repos', 'schedule.useLocationHours': 'Utiliser les horaires du site', 'schedule.locationHoursUnavailable': 'Aucun horaire n’est configuré pour ce site et ce jour.', 'schedule.generatorMode': 'Source du planning', 'schedule.useRegular': 'Utiliser le planning régulier', 'schedule.customDays': 'Définir les jours manuellement', 'schedule.preview': 'Aperçu des services', 'schedule.previewDescription': 'Vérifiez chaque service avant la création. Les conflits seront ignorés.', 'schedule.ready': 'Prêt', 'schedule.duplicate': 'Doublon', 'schedule.overlap': 'Chevauchement', 'schedule.invalid': 'Horaire incorrect', 'schedule.noReady': 'Aucun service valide à créer.', 'schedule.conflictsSkipped': '{count} services en conflit ou incorrects ont été ignorés.', 'schedule.selectReady': 'Inclure le service valide du {date}', 'schedule.recheckConflict': 'Le planning a changé pendant la vérification. Vérifiez les conflits actualisés.', 'schedule.concurrentOverlap': 'Ce service chevauche un autre service du même employé. Actualisez le planning et vérifiez le conflit.', 'schedule.print': 'Imprimer le planning', 'schedule.printTitle': 'Planning des employés', 'schedule.printEmployees': 'Employés à imprimer', 'schedule.printAll': 'Sélectionner tous les employés de cette période', 'schedule.printRequired': 'Sélectionnez au moins un employé ayant des services.', 'schedule.period': 'Période du planning', 'schedule.day': 'Jour', 'schedule.break': 'Pause', 'schedule.duration': 'Temps de travail', 'schedule.weeklyTotal': 'Total des heures', 'schedule.personalNumber': 'Numéro d’employé', 'schedule.noShiftsToPrint': 'Aucun service pour les employés et la période sélectionnés.',
  },
}
