import type { Locale } from '@/lib/i18n'

const en = {
  'employeeNumber.title': 'Employee numbers',
  'employeeNumber.description': 'Configure Personalnummer rules for this workspace.',
  'employeeNumber.label': 'Employee number',
  'employeeNumber.require': 'Require employee number',
  'employeeNumber.requireDescription': 'New or subsequently edited employees must have a number. Existing records are not deleted or changed.',
  'employeeNumber.automatic': 'Automatic numbering',
  'employeeNumber.automaticDescription': 'Leonety assigns the next number safely when an employee is saved.',
  'employeeNumber.prefix': 'Prefix',
  'employeeNumber.next': 'Next number',
  'employeeNumber.minimumDigits': 'Minimum digits',
  'employeeNumber.preview': 'Next number preview: {number}',
  'employeeNumber.assignedOnSave': 'The employee number will be assigned automatically when this employee is saved.',
  'employeeNumber.lockedAutomatic': 'Automatically assigned numbers cannot be edited while automatic numbering is enabled.',
  'employeeNumber.saved': 'Employee number settings saved.',
  'employeeNumber.saveFailed': 'Employee number settings could not be saved.',
  'employeeNumber.loadFailed': 'Employee number settings could not be loaded.',
  'employeeNumber.migrationRequired': 'Apply the reviewed Personalnummer database change before enabling this feature.',
  'employeeNumber.required': 'Enter an employee number.',
  'employeeNumber.duplicate': 'This employee number is already used in this workspace.',
  'employeeNumber.counterDecrease': 'The next number cannot be lower than the current database counter.',
  'employeeNumber.invalidSettings': 'Check the prefix, next number and minimum digits.',
}

type Dictionary = Record<keyof typeof en, string>

export const employeeNumberDictionaries: Record<Locale, Dictionary> = {
  en,
  de: {
    'employeeNumber.title': 'Personalnummern', 'employeeNumber.description': 'Regeln für Personalnummern in diesem Workspace konfigurieren.', 'employeeNumber.label': 'Personalnummer', 'employeeNumber.require': 'Personalnummer erforderlich', 'employeeNumber.requireDescription': 'Neue oder später bearbeitete Mitarbeiter benötigen eine Nummer. Bestehende Datensätze werden weder gelöscht noch verändert.', 'employeeNumber.automatic': 'Automatische Nummerierung', 'employeeNumber.automaticDescription': 'Leonety vergibt beim Speichern sicher die nächste Nummer.', 'employeeNumber.prefix': 'Präfix', 'employeeNumber.next': 'Nächste Nummer', 'employeeNumber.minimumDigits': 'Mindestanzahl Stellen', 'employeeNumber.preview': 'Vorschau der nächsten Nummer: {number}', 'employeeNumber.assignedOnSave': 'Die Personalnummer wird beim Speichern automatisch vergeben.', 'employeeNumber.lockedAutomatic': 'Automatisch vergebene Nummern können bei aktiver automatischer Nummerierung nicht bearbeitet werden.', 'employeeNumber.saved': 'Einstellungen für Personalnummern gespeichert.', 'employeeNumber.saveFailed': 'Die Einstellungen für Personalnummern konnten nicht gespeichert werden.', 'employeeNumber.loadFailed': 'Die Einstellungen für Personalnummern konnten nicht geladen werden.', 'employeeNumber.migrationRequired': 'Wende zuerst die geprüfte Personalnummer-Datenbankänderung an.', 'employeeNumber.required': 'Gib eine Personalnummer ein.', 'employeeNumber.duplicate': 'Diese Personalnummer wird in diesem Workspace bereits verwendet.', 'employeeNumber.counterDecrease': 'Die nächste Nummer darf nicht unter dem aktuellen Datenbankzähler liegen.', 'employeeNumber.invalidSettings': 'Prüfe Präfix, nächste Nummer und Mindestanzahl Stellen.',
  },
  ru: {
    'employeeNumber.title': 'Табельные номера', 'employeeNumber.description': 'Настройте правила Personalnummer для этого рабочего пространства.', 'employeeNumber.label': 'Табельный номер', 'employeeNumber.require': 'Требовать табельный номер', 'employeeNumber.requireDescription': 'Для новых и впоследствии изменяемых сотрудников номер будет обязателен. Существующие записи не удаляются и не изменяются.', 'employeeNumber.automatic': 'Автоматическая нумерация', 'employeeNumber.automaticDescription': 'Leonety безопасно присваивает следующий номер при сохранении сотрудника.', 'employeeNumber.prefix': 'Префикс', 'employeeNumber.next': 'Следующий номер', 'employeeNumber.minimumDigits': 'Минимум цифр', 'employeeNumber.preview': 'Предпросмотр следующего номера: {number}', 'employeeNumber.assignedOnSave': 'Табельный номер будет присвоен автоматически при сохранении сотрудника.', 'employeeNumber.lockedAutomatic': 'Автоматически присвоенный номер нельзя изменить, пока включена автоматическая нумерация.', 'employeeNumber.saved': 'Настройки табельных номеров сохранены.', 'employeeNumber.saveFailed': 'Не удалось сохранить настройки табельных номеров.', 'employeeNumber.loadFailed': 'Не удалось загрузить настройки табельных номеров.', 'employeeNumber.migrationRequired': 'Перед включением функции примените проверенное изменение БД для Personalnummer.', 'employeeNumber.required': 'Введите табельный номер.', 'employeeNumber.duplicate': 'Этот табельный номер уже используется в данном рабочем пространстве.', 'employeeNumber.counterDecrease': 'Следующий номер не может быть меньше текущего счётчика в базе данных.', 'employeeNumber.invalidSettings': 'Проверьте префикс, следующий номер и минимальное число цифр.',
  },
  tr: {
    'employeeNumber.title': 'Personel numaraları', 'employeeNumber.description': 'Bu çalışma alanı için personel numarası kurallarını yapılandırın.', 'employeeNumber.label': 'Personel numarası', 'employeeNumber.require': 'Personel numarası zorunlu', 'employeeNumber.requireDescription': 'Yeni veya daha sonra düzenlenen çalışanların numarası olmalıdır. Mevcut kayıtlar silinmez veya değiştirilmez.', 'employeeNumber.automatic': 'Otomatik numaralandırma', 'employeeNumber.automaticDescription': 'Leonety çalışan kaydedilirken sıradaki numarayı güvenli şekilde atar.', 'employeeNumber.prefix': 'Önek', 'employeeNumber.next': 'Sonraki numara', 'employeeNumber.minimumDigits': 'En az basamak', 'employeeNumber.preview': 'Sonraki numara önizlemesi: {number}', 'employeeNumber.assignedOnSave': 'Çalışan kaydedildiğinde personel numarası otomatik atanacaktır.', 'employeeNumber.lockedAutomatic': 'Otomatik numaralandırma açıkken otomatik atanan numaralar düzenlenemez.', 'employeeNumber.saved': 'Personel numarası ayarları kaydedildi.', 'employeeNumber.saveFailed': 'Personel numarası ayarları kaydedilemedi.', 'employeeNumber.loadFailed': 'Personel numarası ayarları yüklenemedi.', 'employeeNumber.migrationRequired': 'Bu özelliği etkinleştirmeden önce incelenmiş Personalnummer veritabanı değişikliğini uygulayın.', 'employeeNumber.required': 'Bir personel numarası girin.', 'employeeNumber.duplicate': 'Bu personel numarası bu çalışma alanında zaten kullanılıyor.', 'employeeNumber.counterDecrease': 'Sonraki numara mevcut veritabanı sayacından düşük olamaz.', 'employeeNumber.invalidSettings': 'Önek, sonraki numara ve en az basamak değerlerini kontrol edin.',
  },
  uk: {
    'employeeNumber.title': 'Табельні номери', 'employeeNumber.description': 'Налаштуйте правила Personalnummer для цього робочого простору.', 'employeeNumber.label': 'Табельний номер', 'employeeNumber.require': 'Вимагати табельний номер', 'employeeNumber.requireDescription': 'Для нових і згодом змінених працівників номер буде обов’язковим. Наявні записи не видаляються й не змінюються.', 'employeeNumber.automatic': 'Автоматична нумерація', 'employeeNumber.automaticDescription': 'Leonety безпечно присвоює наступний номер під час збереження працівника.', 'employeeNumber.prefix': 'Префікс', 'employeeNumber.next': 'Наступний номер', 'employeeNumber.minimumDigits': 'Мінімум цифр', 'employeeNumber.preview': 'Попередній перегляд наступного номера: {number}', 'employeeNumber.assignedOnSave': 'Табельний номер буде присвоєно автоматично під час збереження працівника.', 'employeeNumber.lockedAutomatic': 'Автоматично присвоєний номер не можна змінити, доки ввімкнено автоматичну нумерацію.', 'employeeNumber.saved': 'Налаштування табельних номерів збережено.', 'employeeNumber.saveFailed': 'Не вдалося зберегти налаштування табельних номерів.', 'employeeNumber.loadFailed': 'Не вдалося завантажити налаштування табельних номерів.', 'employeeNumber.migrationRequired': 'Перед увімкненням функції застосуйте перевірену зміну БД для Personalnummer.', 'employeeNumber.required': 'Введіть табельний номер.', 'employeeNumber.duplicate': 'Цей табельний номер уже використовується в цьому робочому просторі.', 'employeeNumber.counterDecrease': 'Наступний номер не може бути меншим за поточний лічильник у базі даних.', 'employeeNumber.invalidSettings': 'Перевірте префікс, наступний номер і мінімальну кількість цифр.',
  },
  pl: {
    'employeeNumber.title': 'Numery pracowników', 'employeeNumber.description': 'Skonfiguruj zasady numerów pracowników dla tego obszaru roboczego.', 'employeeNumber.label': 'Numer pracownika', 'employeeNumber.require': 'Wymagaj numeru pracownika', 'employeeNumber.requireDescription': 'Nowi lub później edytowani pracownicy muszą mieć numer. Istniejące rekordy nie są usuwane ani zmieniane.', 'employeeNumber.automatic': 'Automatyczna numeracja', 'employeeNumber.automaticDescription': 'Leonety bezpiecznie nadaje kolejny numer podczas zapisywania pracownika.', 'employeeNumber.prefix': 'Prefiks', 'employeeNumber.next': 'Następny numer', 'employeeNumber.minimumDigits': 'Minimalna liczba cyfr', 'employeeNumber.preview': 'Podgląd następnego numeru: {number}', 'employeeNumber.assignedOnSave': 'Numer pracownika zostanie nadany automatycznie podczas zapisywania.', 'employeeNumber.lockedAutomatic': 'Automatycznie nadanych numerów nie można edytować przy włączonej automatycznej numeracji.', 'employeeNumber.saved': 'Ustawienia numerów pracowników zapisano.', 'employeeNumber.saveFailed': 'Nie udało się zapisać ustawień numerów pracowników.', 'employeeNumber.loadFailed': 'Nie udało się wczytać ustawień numerów pracowników.', 'employeeNumber.migrationRequired': 'Przed włączeniem funkcji zastosuj sprawdzoną zmianę bazy danych Personalnummer.', 'employeeNumber.required': 'Wpisz numer pracownika.', 'employeeNumber.duplicate': 'Ten numer pracownika jest już używany w tym obszarze roboczym.', 'employeeNumber.counterDecrease': 'Następny numer nie może być mniejszy niż bieżący licznik w bazie danych.', 'employeeNumber.invalidSettings': 'Sprawdź prefiks, następny numer i minimalną liczbę cyfr.',
  },
  fr: {
    'employeeNumber.title': 'Matricules salariés', 'employeeNumber.description': 'Configurez les règles de matricule pour cet espace de travail.', 'employeeNumber.label': 'Matricule salarié', 'employeeNumber.require': 'Matricule obligatoire', 'employeeNumber.requireDescription': 'Les salariés nouveaux ou modifiés ultérieurement doivent avoir un matricule. Les enregistrements existants ne sont ni supprimés ni modifiés.', 'employeeNumber.automatic': 'Numérotation automatique', 'employeeNumber.automaticDescription': 'Leonety attribue de façon sûre le prochain numéro lors de l’enregistrement.', 'employeeNumber.prefix': 'Préfixe', 'employeeNumber.next': 'Prochain numéro', 'employeeNumber.minimumDigits': 'Nombre minimal de chiffres', 'employeeNumber.preview': 'Aperçu du prochain numéro : {number}', 'employeeNumber.assignedOnSave': 'Le matricule sera attribué automatiquement lors de l’enregistrement du salarié.', 'employeeNumber.lockedAutomatic': 'Les matricules attribués automatiquement ne peuvent pas être modifiés tant que la numérotation automatique est active.', 'employeeNumber.saved': 'Paramètres des matricules enregistrés.', 'employeeNumber.saveFailed': 'Les paramètres des matricules n’ont pas pu être enregistrés.', 'employeeNumber.loadFailed': 'Les paramètres des matricules n’ont pas pu être chargés.', 'employeeNumber.migrationRequired': 'Appliquez la modification de base de données Personalnummer validée avant d’activer cette fonction.', 'employeeNumber.required': 'Saisissez un matricule salarié.', 'employeeNumber.duplicate': 'Ce matricule est déjà utilisé dans cet espace de travail.', 'employeeNumber.counterDecrease': 'Le prochain numéro ne peut pas être inférieur au compteur actuel de la base.', 'employeeNumber.invalidSettings': 'Vérifiez le préfixe, le prochain numéro et le nombre minimal de chiffres.',
  },
}
