import type { Locale } from '@/lib/i18n'

type Dictionary = Record<string, string>

export const financeUiDictionaries: Record<Locale, Dictionary> = {
  en: { 'finance.filters': 'Filters and sorting', 'finance.utilities': 'Import, export and print', 'finance.actions': 'Actions', 'finance.search': 'Search records', 'finance.searchPlaceholder': 'Search title, description or category', 'finance.selectVisible': 'Select visible', 'finance.selectedCount': '{count} selected', 'finance.filteredEmptyTitle': 'No results for current filters', 'finance.filteredEmptyDescription': 'Adjust the search, date range or filters to see more records.', 'finance.pagination': 'Page {page} of {pages} · {total} records', 'finance.previous': 'Previous', 'finance.next': 'Next' },
  de: { 'finance.filters': 'Filter und Sortierung', 'finance.utilities': 'Import, Export und Drucken', 'finance.actions': 'Aktionen', 'finance.search': 'Einträge suchen', 'finance.searchPlaceholder': 'Titel, Beschreibung oder Kategorie suchen', 'finance.selectVisible': 'Sichtbare auswählen', 'finance.selectedCount': '{count} ausgewählt', 'finance.filteredEmptyTitle': 'Keine Ergebnisse für die aktuellen Filter', 'finance.filteredEmptyDescription': 'Passe Suche, Zeitraum oder Filter an, um weitere Einträge zu sehen.', 'finance.pagination': 'Seite {page} von {pages} · {total} Einträge', 'finance.previous': 'Zurück', 'finance.next': 'Weiter' },
  ru: { 'finance.filters': 'Фильтры и сортировка', 'finance.utilities': 'Импорт, экспорт и печать', 'finance.actions': 'Действия', 'finance.search': 'Поиск записей', 'finance.searchPlaceholder': 'Поиск по названию, описанию или категории', 'finance.selectVisible': 'Выбрать видимые', 'finance.selectedCount': 'Выбрано: {count}', 'finance.filteredEmptyTitle': 'По текущим фильтрам ничего не найдено', 'finance.filteredEmptyDescription': 'Измените поиск, период или фильтры, чтобы увидеть другие записи.', 'finance.pagination': 'Страница {page} из {pages} · записей: {total}', 'finance.previous': 'Назад', 'finance.next': 'Далее' },
  tr: { 'finance.filters': 'Filtreler ve sıralama', 'finance.utilities': 'İçe aktarma, dışa aktarma ve yazdırma', 'finance.actions': 'İşlemler', 'finance.search': 'Kayıtlarda ara', 'finance.searchPlaceholder': 'Başlık, açıklama veya kategori ara', 'finance.selectVisible': 'Görünenleri seç', 'finance.selectedCount': '{count} seçildi', 'finance.filteredEmptyTitle': 'Geçerli filtreler için sonuç yok', 'finance.filteredEmptyDescription': 'Daha fazla kayıt görmek için aramayı, tarih aralığını veya filtreleri değiştirin.', 'finance.pagination': 'Sayfa {page}/{pages} · {total} kayıt', 'finance.previous': 'Önceki', 'finance.next': 'Sonraki' },
  uk: { 'finance.filters': 'Фільтри та сортування', 'finance.utilities': 'Імпорт, експорт і друк', 'finance.actions': 'Дії', 'finance.search': 'Пошук записів', 'finance.searchPlaceholder': 'Пошук за назвою, описом або категорією', 'finance.selectVisible': 'Вибрати видимі', 'finance.selectedCount': 'Вибрано: {count}', 'finance.filteredEmptyTitle': 'За поточними фільтрами нічого не знайдено', 'finance.filteredEmptyDescription': 'Змініть пошук, період або фільтри, щоб побачити інші записи.', 'finance.pagination': 'Сторінка {page} з {pages} · записів: {total}', 'finance.previous': 'Назад', 'finance.next': 'Далі' },
  pl: { 'finance.filters': 'Filtry i sortowanie', 'finance.utilities': 'Import, eksport i drukowanie', 'finance.actions': 'Działania', 'finance.search': 'Szukaj wpisów', 'finance.searchPlaceholder': 'Szukaj tytułu, opisu lub kategorii', 'finance.selectVisible': 'Wybierz widoczne', 'finance.selectedCount': 'Wybrano: {count}', 'finance.filteredEmptyTitle': 'Brak wyników dla bieżących filtrów', 'finance.filteredEmptyDescription': 'Zmień wyszukiwanie, zakres dat lub filtry, aby zobaczyć więcej wpisów.', 'finance.pagination': 'Strona {page} z {pages} · wpisów: {total}', 'finance.previous': 'Wstecz', 'finance.next': 'Dalej' },
  fr: { 'finance.filters': 'Filtres et tri', 'finance.utilities': 'Import, export et impression', 'finance.actions': 'Actions', 'finance.search': 'Rechercher des éléments', 'finance.searchPlaceholder': 'Rechercher un titre, une description ou une catégorie', 'finance.selectVisible': 'Sélectionner les éléments visibles', 'finance.selectedCount': '{count} sélectionné(s)', 'finance.filteredEmptyTitle': 'Aucun résultat pour les filtres actuels', 'finance.filteredEmptyDescription': 'Modifiez la recherche, la période ou les filtres pour afficher davantage d’éléments.', 'finance.pagination': 'Page {page} sur {pages} · {total} éléments', 'finance.previous': 'Précédent', 'finance.next': 'Suivant' },
}
