const en = {
  title:'Product import / export', description:'Review product data before anything is saved.', importTab:'Import', exportTab:'Export',
  chooseFile:'Choose CSV file', supportedFiles:'CSV up to 5 MB and 5,000 product rows.', parse:'Parse file', format:'Format', leonety:'Leonety CSV', woocommerce:'WooCommerce CSV', shopify:'Shopify CSV', googleBasic:'Google catalog CSV (basic)',
  mappingTitle:'Match CSV columns', mappingDescription:'Choose which CSV column belongs to each Leonety field.', ignore:'Ignore', preview:'Validate and preview',
  name:'Name', descriptionField:'Description', sku:'SKU / article number', barcode:'Barcode', category:'Category', price:'Selling price', currency:'Currency', stock:'Stock', imageUrl:'Image URL', status:'Status', externalId:'Provider product ID',
  reviewTitle:'Import preview', reviewDescription:'New rows are selected by default. Existing products require explicit selection before they are updated.',
  stateNew:'New', stateExisting:'Existing / matched', stateConflict:'Conflict', stateInvalid:'Invalid', selected:'Selected', row:'Row', matchedProduct:'Matched product', validation:'Validation',
  nameRequired:'Product name is required.', priceInvalid:'Price must be a non-negative number.', stockInvalid:'Stock must be a non-negative whole number.', duplicateSku:'Duplicate SKU in this file.', duplicateBarcode:'Duplicate barcode in this file.', duplicateExternal:'Duplicate provider ID in this file.', identifiersConflict:'Identifiers match different existing products.',
  selectAllSafe:'Select all new products', updateWarning:'Selected existing products will be updated only after confirmation.', confirmImport:'Import selected', importing:'Importing...', importSuccess:'Created {created}; updated {updated}.', previewChanged:'Product data changed after preview. Review the file again.', duplicateIdentifier:'A SKU or barcode now conflicts with an existing product.', importFailed:'Products could not be imported.', malformed:'This CSV is empty, malformed, or has duplicate column names.', tooLarge:'The CSV exceeds the supported size or row limit.', nothingSelected:'Select at least one valid row.',
  exportScope:'Products to export', scopeSelected:'Selected products', scopeVisible:'Visible / filtered products', scopeAll:'All workspace products', selectedCount:'{count} selected', visibleCount:'{count} visible', allCount:'{count} total', exportFormat:'Export format', export:'Download CSV', exporting:'Preparing...', exportFailed:'The CSV could not be exported.', googleNotice:'This is a basic catalog structure. Review required Merchant fields before uploading it to Google.', close:'Close', back:'Back', cancel:'Cancel',
}

const de: typeof en = {
  title:'Produktimport / -export',description:'Produktdaten prüfen, bevor etwas gespeichert wird.',importTab:'Importieren',exportTab:'Exportieren',chooseFile:'CSV-Datei auswählen',supportedFiles:'CSV bis 5 MB und 5.000 Produktzeilen.',parse:'Datei einlesen',format:'Format',leonety:'Leonety CSV',woocommerce:'WooCommerce CSV',shopify:'Shopify CSV',googleBasic:'Google-Katalog-CSV (Basis)',mappingTitle:'CSV-Spalten zuordnen',mappingDescription:'Wähle, welche CSV-Spalte zu welchem Leonety-Feld gehört.',ignore:'Ignorieren',preview:'Prüfen und Vorschau',name:'Name',descriptionField:'Beschreibung',sku:'SKU / Artikelnummer',barcode:'Barcode',category:'Kategorie',price:'Verkaufspreis',currency:'Währung',stock:'Bestand',imageUrl:'Bild-URL',status:'Status',externalId:'Produkt-ID des Anbieters',reviewTitle:'Importvorschau',reviewDescription:'Neue Zeilen sind vorausgewählt. Bestehende Produkte müssen vor einer Aktualisierung ausdrücklich ausgewählt werden.',stateNew:'Neu',stateExisting:'Vorhanden / zugeordnet',stateConflict:'Konflikt',stateInvalid:'Ungültig',selected:'Ausgewählt',row:'Zeile',matchedProduct:'Zugeordnetes Produkt',validation:'Prüfung',nameRequired:'Produktname ist erforderlich.',priceInvalid:'Der Preis muss eine nicht negative Zahl sein.',stockInvalid:'Der Bestand muss eine nicht negative ganze Zahl sein.',duplicateSku:'Doppelte SKU in dieser Datei.',duplicateBarcode:'Doppelter Barcode in dieser Datei.',duplicateExternal:'Doppelte Anbieter-ID in dieser Datei.',identifiersConflict:'Kennungen passen zu unterschiedlichen bestehenden Produkten.',selectAllSafe:'Alle neuen Produkte auswählen',updateWarning:'Ausgewählte bestehende Produkte werden erst nach Bestätigung aktualisiert.',confirmImport:'Auswahl importieren',importing:'Import läuft...',importSuccess:'Erstellt: {created}; aktualisiert: {updated}.',previewChanged:'Produktdaten haben sich nach der Vorschau geändert. Datei erneut prüfen.',duplicateIdentifier:'Eine SKU oder ein Barcode kollidiert jetzt mit einem bestehenden Produkt.',importFailed:'Produkte konnten nicht importiert werden.',malformed:'Die CSV ist leer, fehlerhaft oder enthält doppelte Spaltennamen.',tooLarge:'Die CSV überschreitet die zulässige Größe oder Zeilenzahl.',nothingSelected:'Wähle mindestens eine gültige Zeile aus.',exportScope:'Zu exportierende Produkte',scopeSelected:'Ausgewählte Produkte',scopeVisible:'Sichtbare / gefilterte Produkte',scopeAll:'Alle Produkte des Arbeitsbereichs',selectedCount:'{count} ausgewählt',visibleCount:'{count} sichtbar',allCount:'{count} insgesamt',exportFormat:'Exportformat',export:'CSV herunterladen',exporting:'Wird vorbereitet...',exportFailed:'Die CSV konnte nicht exportiert werden.',googleNotice:'Dies ist eine grundlegende Katalogstruktur. Prüfe die erforderlichen Merchant-Felder vor dem Google-Upload.',close:'Schließen',back:'Zurück',cancel:'Abbrechen',
}

const ru: typeof en = {
  title:'Импорт / экспорт товаров',description:'Проверьте данные до их сохранения.',importTab:'Импорт',exportTab:'Экспорт',chooseFile:'Выбрать CSV-файл',supportedFiles:'CSV до 5 МБ и 5 000 строк товаров.',parse:'Прочитать файл',format:'Формат',leonety:'Leonety CSV',woocommerce:'WooCommerce CSV',shopify:'Shopify CSV',googleBasic:'CSV каталога Google (базовый)',mappingTitle:'Сопоставление столбцов CSV',mappingDescription:'Укажите, какому полю Leonety соответствует каждый столбец CSV.',ignore:'Игнорировать',preview:'Проверить и показать',name:'Название',descriptionField:'Описание',sku:'SKU / артикул',barcode:'Штрихкод',category:'Категория',price:'Цена продажи',currency:'Валюта',stock:'Остаток',imageUrl:'URL изображения',status:'Статус',externalId:'ID товара у провайдера',reviewTitle:'Предпросмотр импорта',reviewDescription:'Новые строки выбраны по умолчанию. Обновление существующих товаров требует явного выбора.',stateNew:'Новый',stateExisting:'Существующий / найден',stateConflict:'Конфликт',stateInvalid:'Некорректный',selected:'Выбрано',row:'Строка',matchedProduct:'Найденный товар',validation:'Проверка',nameRequired:'Название товара обязательно.',priceInvalid:'Цена должна быть неотрицательным числом.',stockInvalid:'Остаток должен быть неотрицательным целым числом.',duplicateSku:'SKU повторяется в этом файле.',duplicateBarcode:'Штрихкод повторяется в этом файле.',duplicateExternal:'ID провайдера повторяется в этом файле.',identifiersConflict:'Идентификаторы относятся к разным существующим товарам.',selectAllSafe:'Выбрать все новые товары',updateWarning:'Выбранные существующие товары обновятся только после подтверждения.',confirmImport:'Импортировать выбранное',importing:'Импорт...',importSuccess:'Создано: {created}; обновлено: {updated}.',previewChanged:'После предпросмотра данные изменились. Проверьте файл заново.',duplicateIdentifier:'SKU или штрихкод теперь конфликтует с существующим товаром.',importFailed:'Не удалось импортировать товары.',malformed:'CSV пуст, повреждён или содержит повторяющиеся заголовки.',tooLarge:'CSV превышает допустимый размер или число строк.',nothingSelected:'Выберите хотя бы одну корректную строку.',exportScope:'Какие товары экспортировать',scopeSelected:'Выбранные товары',scopeVisible:'Видимые / отфильтрованные товары',scopeAll:'Все товары рабочего пространства',selectedCount:'Выбрано: {count}',visibleCount:'Видимо: {count}',allCount:'Всего: {count}',exportFormat:'Формат экспорта',export:'Скачать CSV',exporting:'Подготовка...',exportFailed:'Не удалось экспортировать CSV.',googleNotice:'Это базовая структура каталога. Перед загрузкой в Google проверьте обязательные поля Merchant.',close:'Закрыть',back:'Назад',cancel:'Отмена',
}

const tr: typeof en = {
  title:'Ürün içe / dışa aktarma',description:'Herhangi bir veri kaydedilmeden önce ürünleri inceleyin.',importTab:'İçe aktar',exportTab:'Dışa aktar',chooseFile:'CSV dosyası seç',supportedFiles:'En fazla 5 MB ve 5.000 ürün satırı.',parse:'Dosyayı oku',format:'Biçim',leonety:'Leonety CSV',woocommerce:'WooCommerce CSV',shopify:'Shopify CSV',googleBasic:'Google katalog CSV (temel)',mappingTitle:'CSV sütunlarını eşleştir',mappingDescription:'Her CSV sütununun hangi Leonety alanına ait olduğunu seçin.',ignore:'Yoksay',preview:'Doğrula ve önizle',name:'Ad',descriptionField:'Açıklama',sku:'SKU / ürün numarası',barcode:'Barkod',category:'Kategori',price:'Satış fiyatı',currency:'Para birimi',stock:'Stok',imageUrl:'Görsel URL',status:'Durum',externalId:'Sağlayıcı ürün kimliği',reviewTitle:'İçe aktarma önizlemesi',reviewDescription:'Yeni satırlar varsayılan olarak seçilir. Mevcut ürünleri güncellemek için açıkça seçmelisiniz.',stateNew:'Yeni',stateExisting:'Mevcut / eşleşen',stateConflict:'Çakışma',stateInvalid:'Geçersiz',selected:'Seçili',row:'Satır',matchedProduct:'Eşleşen ürün',validation:'Doğrulama',nameRequired:'Ürün adı zorunludur.',priceInvalid:'Fiyat negatif olmayan bir sayı olmalıdır.',stockInvalid:'Stok negatif olmayan tam sayı olmalıdır.',duplicateSku:'Bu dosyada yinelenen SKU.',duplicateBarcode:'Bu dosyada yinelenen barkod.',duplicateExternal:'Bu dosyada yinelenen sağlayıcı kimliği.',identifiersConflict:'Kimlikler farklı mevcut ürünlerle eşleşiyor.',selectAllSafe:'Tüm yeni ürünleri seç',updateWarning:'Seçili mevcut ürünler yalnızca onaydan sonra güncellenir.',confirmImport:'Seçilenleri içe aktar',importing:'İçe aktarılıyor...',importSuccess:'Oluşturulan: {created}; güncellenen: {updated}.',previewChanged:'Önizlemeden sonra ürün verileri değişti. Dosyayı yeniden inceleyin.',duplicateIdentifier:'SKU veya barkod artık mevcut bir ürünle çakışıyor.',importFailed:'Ürünler içe aktarılamadı.',malformed:'CSV boş, bozuk veya yinelenen sütun adları içeriyor.',tooLarge:'CSV desteklenen boyut veya satır sınırını aşıyor.',nothingSelected:'En az bir geçerli satır seçin.',exportScope:'Dışa aktarılacak ürünler',scopeSelected:'Seçili ürünler',scopeVisible:'Görünür / filtrelenmiş ürünler',scopeAll:'Çalışma alanındaki tüm ürünler',selectedCount:'{count} seçili',visibleCount:'{count} görünür',allCount:'Toplam {count}',exportFormat:'Dışa aktarma biçimi',export:'CSV indir',exporting:'Hazırlanıyor...',exportFailed:'CSV dışa aktarılamadı.',googleNotice:'Bu temel bir katalog yapısıdır. Google yüklemesinden önce gerekli Merchant alanlarını inceleyin.',close:'Kapat',back:'Geri',cancel:'İptal',
}

const uk: typeof en = {
  title:'Імпорт / експорт товарів',description:'Перевірте дані товарів перед збереженням.',importTab:'Імпорт',exportTab:'Експорт',chooseFile:'Вибрати CSV-файл',supportedFiles:'CSV до 5 МБ і 5 000 рядків товарів.',parse:'Прочитати файл',format:'Формат',leonety:'Leonety CSV',woocommerce:'WooCommerce CSV',shopify:'Shopify CSV',googleBasic:'CSV каталогу Google (базовий)',mappingTitle:'Зіставлення стовпців CSV',mappingDescription:'Виберіть, якому полю Leonety відповідає кожен стовпець CSV.',ignore:'Ігнорувати',preview:'Перевірити й показати',name:'Назва',descriptionField:'Опис',sku:'SKU / артикул',barcode:'Штрихкод',category:'Категорія',price:'Ціна продажу',currency:'Валюта',stock:'Залишок',imageUrl:'URL зображення',status:'Статус',externalId:'ID товару провайдера',reviewTitle:'Попередній перегляд імпорту',reviewDescription:'Нові рядки вибрано за замовчуванням. Оновлення наявних товарів потребує явного вибору.',stateNew:'Новий',stateExisting:'Наявний / знайдений',stateConflict:'Конфлікт',stateInvalid:'Некоректний',selected:'Вибрано',row:'Рядок',matchedProduct:'Знайдений товар',validation:'Перевірка',nameRequired:'Назва товару обов’язкова.',priceInvalid:'Ціна має бути невід’ємним числом.',stockInvalid:'Залишок має бути невід’ємним цілим числом.',duplicateSku:'SKU повторюється в цьому файлі.',duplicateBarcode:'Штрихкод повторюється в цьому файлі.',duplicateExternal:'ID провайдера повторюється в цьому файлі.',identifiersConflict:'Ідентифікатори відповідають різним наявним товарам.',selectAllSafe:'Вибрати всі нові товари',updateWarning:'Вибрані наявні товари буде оновлено лише після підтвердження.',confirmImport:'Імпортувати вибране',importing:'Імпорт...',importSuccess:'Створено: {created}; оновлено: {updated}.',previewChanged:'Після перегляду дані змінилися. Перевірте файл повторно.',duplicateIdentifier:'SKU або штрихкод тепер конфліктує з наявним товаром.',importFailed:'Не вдалося імпортувати товари.',malformed:'CSV порожній, пошкоджений або містить повторювані заголовки.',tooLarge:'CSV перевищує допустимий розмір або кількість рядків.',nothingSelected:'Виберіть хоча б один коректний рядок.',exportScope:'Які товари експортувати',scopeSelected:'Вибрані товари',scopeVisible:'Видимі / відфільтровані товари',scopeAll:'Усі товари робочого простору',selectedCount:'Вибрано: {count}',visibleCount:'Видимо: {count}',allCount:'Усього: {count}',exportFormat:'Формат експорту',export:'Завантажити CSV',exporting:'Підготовка...',exportFailed:'Не вдалося експортувати CSV.',googleNotice:'Це базова структура каталогу. Перед завантаженням у Google перевірте обов’язкові поля Merchant.',close:'Закрити',back:'Назад',cancel:'Скасувати',
}

const pl: typeof en = {
  title:'Import / eksport produktów',description:'Sprawdź dane produktów, zanim cokolwiek zostanie zapisane.',importTab:'Import',exportTab:'Eksport',chooseFile:'Wybierz plik CSV',supportedFiles:'CSV do 5 MB i 5 000 wierszy produktów.',parse:'Odczytaj plik',format:'Format',leonety:'Leonety CSV',woocommerce:'WooCommerce CSV',shopify:'Shopify CSV',googleBasic:'CSV katalogu Google (podstawowy)',mappingTitle:'Dopasowanie kolumn CSV',mappingDescription:'Wybierz, któremu polu Leonety odpowiada każda kolumna CSV.',ignore:'Ignoruj',preview:'Sprawdź i wyświetl',name:'Nazwa',descriptionField:'Opis',sku:'SKU / numer artykułu',barcode:'Kod kreskowy',category:'Kategoria',price:'Cena sprzedaży',currency:'Waluta',stock:'Stan',imageUrl:'URL obrazu',status:'Status',externalId:'ID produktu dostawcy',reviewTitle:'Podgląd importu',reviewDescription:'Nowe wiersze są domyślnie wybrane. Aktualizacja istniejących produktów wymaga jawnego wyboru.',stateNew:'Nowy',stateExisting:'Istniejący / dopasowany',stateConflict:'Konflikt',stateInvalid:'Nieprawidłowy',selected:'Wybrane',row:'Wiersz',matchedProduct:'Dopasowany produkt',validation:'Walidacja',nameRequired:'Nazwa produktu jest wymagana.',priceInvalid:'Cena musi być liczbą nieujemną.',stockInvalid:'Stan musi być nieujemną liczbą całkowitą.',duplicateSku:'Powtórzony SKU w tym pliku.',duplicateBarcode:'Powtórzony kod kreskowy w tym pliku.',duplicateExternal:'Powtórzone ID dostawcy w tym pliku.',identifiersConflict:'Identyfikatory pasują do różnych istniejących produktów.',selectAllSafe:'Wybierz wszystkie nowe produkty',updateWarning:'Wybrane istniejące produkty zostaną zaktualizowane dopiero po potwierdzeniu.',confirmImport:'Importuj wybrane',importing:'Importowanie...',importSuccess:'Utworzono: {created}; zaktualizowano: {updated}.',previewChanged:'Dane produktów zmieniły się po podglądzie. Sprawdź plik ponownie.',duplicateIdentifier:'SKU lub kod kreskowy koliduje teraz z istniejącym produktem.',importFailed:'Nie udało się zaimportować produktów.',malformed:'CSV jest pusty, uszkodzony lub zawiera powtórzone nazwy kolumn.',tooLarge:'CSV przekracza obsługiwany rozmiar lub limit wierszy.',nothingSelected:'Wybierz co najmniej jeden prawidłowy wiersz.',exportScope:'Produkty do eksportu',scopeSelected:'Wybrane produkty',scopeVisible:'Widoczne / filtrowane produkty',scopeAll:'Wszystkie produkty przestrzeni roboczej',selectedCount:'Wybrano: {count}',visibleCount:'Widoczne: {count}',allCount:'Razem: {count}',exportFormat:'Format eksportu',export:'Pobierz CSV',exporting:'Przygotowywanie...',exportFailed:'Nie udało się wyeksportować CSV.',googleNotice:'To podstawowa struktura katalogu. Przed wysłaniem do Google sprawdź wymagane pola Merchant.',close:'Zamknij',back:'Wstecz',cancel:'Anuluj',
}

const fr: typeof en = {
  title:'Import / export de produits',description:'Vérifiez les données avant tout enregistrement.',importTab:'Importer',exportTab:'Exporter',chooseFile:'Choisir un fichier CSV',supportedFiles:'CSV de 5 Mo et 5 000 lignes produit maximum.',parse:'Lire le fichier',format:'Format',leonety:'CSV Leonety',woocommerce:'CSV WooCommerce',shopify:'CSV Shopify',googleBasic:'CSV catalogue Google (basique)',mappingTitle:'Associer les colonnes CSV',mappingDescription:'Choisissez le champ Leonety correspondant à chaque colonne CSV.',ignore:'Ignorer',preview:'Valider et prévisualiser',name:'Nom',descriptionField:'Description',sku:'SKU / référence',barcode:'Code-barres',category:'Catégorie',price:'Prix de vente',currency:'Devise',stock:'Stock',imageUrl:'URL de l’image',status:'Statut',externalId:'ID produit du fournisseur',reviewTitle:'Aperçu de l’import',reviewDescription:'Les nouvelles lignes sont sélectionnées par défaut. La mise à jour d’un produit existant exige une sélection explicite.',stateNew:'Nouveau',stateExisting:'Existant / associé',stateConflict:'Conflit',stateInvalid:'Invalide',selected:'Sélectionné',row:'Ligne',matchedProduct:'Produit associé',validation:'Validation',nameRequired:'Le nom du produit est obligatoire.',priceInvalid:'Le prix doit être un nombre positif ou nul.',stockInvalid:'Le stock doit être un entier positif ou nul.',duplicateSku:'SKU en double dans ce fichier.',duplicateBarcode:'Code-barres en double dans ce fichier.',duplicateExternal:'ID fournisseur en double dans ce fichier.',identifiersConflict:'Les identifiants correspondent à différents produits existants.',selectAllSafe:'Sélectionner tous les nouveaux produits',updateWarning:'Les produits existants sélectionnés seront mis à jour uniquement après confirmation.',confirmImport:'Importer la sélection',importing:'Importation...',importSuccess:'Créés : {created} ; mis à jour : {updated}.',previewChanged:'Les données ont changé après l’aperçu. Vérifiez à nouveau le fichier.',duplicateIdentifier:'Un SKU ou code-barres est maintenant en conflit avec un produit existant.',importFailed:'Impossible d’importer les produits.',malformed:'Le CSV est vide, incorrect ou contient des noms de colonnes en double.',tooLarge:'Le CSV dépasse la taille ou le nombre de lignes autorisé.',nothingSelected:'Sélectionnez au moins une ligne valide.',exportScope:'Produits à exporter',scopeSelected:'Produits sélectionnés',scopeVisible:'Produits visibles / filtrés',scopeAll:'Tous les produits de l’espace',selectedCount:'{count} sélectionnés',visibleCount:'{count} visibles',allCount:'{count} au total',exportFormat:'Format d’export',export:'Télécharger le CSV',exporting:'Préparation...',exportFailed:'Impossible d’exporter le CSV.',googleNotice:'Il s’agit d’une structure de catalogue basique. Vérifiez les champs Merchant requis avant l’envoi à Google.',close:'Fermer',back:'Retour',cancel:'Annuler',
}

function prefix(dictionary: typeof en) {
  return Object.fromEntries(Object.entries(dictionary).map(([key, value]) => [`productCsv.${key}`, value]))
}

export const productCsvDictionaries = { en:prefix(en),de:prefix(de),ru:prefix(ru),tr:prefix(tr),uk:prefix(uk),pl:prefix(pl),fr:prefix(fr) } as const
