import type { Locale } from '@/lib/i18n'

const en = {
  photoImport: 'Import products from photo', photoImportDescription: 'Extract visible menu items into editable drafts. Nothing is saved until you review and confirm it.',
  choosePhoto: 'Choose menu or product photo', analyzePhoto: 'Analyze photo', analyzing: 'Analyzing photo...', supportedPhoto: 'JPEG, PNG or WebP, maximum 8 MB.',
  reviewTitle: 'Review product drafts', reviewDescription: 'Check every field. A printed position is mapped to SKU only after confirmation.',
  include: 'Include', position: 'Position / article', draftName: 'Product name', draftDescription: 'Description', draftPrice: 'Price', draftCategory: 'Category', validation: 'Validation',
  noDrafts: 'No credible products were found in this image.', nameRequired: 'Name is required.', invalidPrice: 'Enter a valid non-negative price.',
  duplicateSkuExisting: 'This SKU already belongs to an existing product: {name}.', duplicateSkuDraft: 'This SKU is repeated in another selected draft: {name}.', resolveDuplicate: 'Edit the SKU or exclude this row before importing.',
  selectedDraftCount: '{count} drafts selected', confirmImport: 'Import selected products', importing: 'Importing products...', imported: '{count} products imported.', importFailed: 'Products could not be imported.',
  extractionFailed: 'The photo could not be analyzed. Check the image and AI configuration, then try again.', providerMissing: 'The configured AI provider is not available for image analysis.', unsupportedImage: 'Use a valid JPEG, PNG or WebP image.',
  menuCreate: 'Create menu', menuDescription: 'Build a printable menu from the selected Leonety products without changing product records.', selectProductsFirst: 'Select at least one product first.',
  template: 'Template', templateClassic: 'Classic', templateModern: 'Modern', templateMinimal: 'Minimal', templateBold: 'Bold', templateCustom: 'Custom reference',
  customReference: 'Upload template reference', customReferenceHint: 'Leonety derives a color direction only. Text and products in the reference image are never copied into the menu.', customReferenceFailed: 'The reference image could not be read.', referencePreview: 'Reference image',
  showDescriptions: 'Show descriptions', showImages: 'Show product images', showArticles: 'Show article numbers', preview: 'Menu preview', printPdf: 'Print / Save as PDF',
  menuEmpty: 'No selected products are available for the menu.', menuTitle: 'Menu', uncategorized: 'Other', selectedProductsCount: '{count} selected products', close: 'Close',
}

type Labels = { [Key in keyof typeof en]: string }

const de: Labels = {
  photoImport:'Produkte aus Foto importieren',photoImportDescription:'Sichtbare Menüpositionen werden als bearbeitbare Entwürfe extrahiert. Vor Prüfung und Bestätigung wird nichts gespeichert.',choosePhoto:'Menü- oder Produktfoto auswählen',analyzePhoto:'Foto analysieren',analyzing:'Foto wird analysiert...',supportedPhoto:'JPEG, PNG oder WebP, maximal 8 MB.',reviewTitle:'Produktentwürfe prüfen',reviewDescription:'Prüfe jedes Feld. Eine gedruckte Position wird erst nach Bestätigung der SKU zugeordnet.',include:'Übernehmen',position:'Position / Artikel',draftName:'Produktname',draftDescription:'Beschreibung',draftPrice:'Preis',draftCategory:'Kategorie',validation:'Prüfung',noDrafts:'Auf diesem Bild wurden keine verlässlichen Produkte erkannt.',nameRequired:'Name ist erforderlich.',invalidPrice:'Gib einen gültigen, nicht negativen Preis ein.',duplicateSkuExisting:'Diese SKU gehört bereits zu einem Produkt: {name}.',duplicateSkuDraft:'Diese SKU wird in einem anderen ausgewählten Entwurf wiederholt: {name}.',resolveDuplicate:'Bearbeite die SKU oder schließe diese Zeile vor dem Import aus.',selectedDraftCount:'{count} Entwürfe ausgewählt',confirmImport:'Ausgewählte Produkte importieren',importing:'Produkte werden importiert...',imported:'{count} Produkte importiert.',importFailed:'Produkte konnten nicht importiert werden.',extractionFailed:'Das Foto konnte nicht analysiert werden. Prüfe Bild und KI-Konfiguration und versuche es erneut.',providerMissing:'Der konfigurierte KI-Anbieter ist für die Bildanalyse nicht verfügbar.',unsupportedImage:'Verwende ein gültiges JPEG-, PNG- oder WebP-Bild.',menuCreate:'Menü erstellen',menuDescription:'Erstelle ein druckbares Menü aus ausgewählten Leonety-Produkten, ohne Produktdaten zu ändern.',selectProductsFirst:'Wähle zuerst mindestens ein Produkt aus.',template:'Vorlage',templateClassic:'Klassisch',templateModern:'Modern',templateMinimal:'Minimal',templateBold:'Kräftig',templateCustom:'Eigene Referenz',customReference:'Vorlagenreferenz hochladen',customReferenceHint:'Leonety übernimmt nur eine Farbrichtung. Texte und Produkte aus dem Referenzbild werden nie in das Menü kopiert.',customReferenceFailed:'Das Referenzbild konnte nicht gelesen werden.',referencePreview:'Referenzbild',showDescriptions:'Beschreibungen anzeigen',showImages:'Produktbilder anzeigen',showArticles:'Artikelnummern anzeigen',preview:'Menüvorschau',printPdf:'Drucken / Als PDF speichern',menuEmpty:'Für das Menü sind keine ausgewählten Produkte verfügbar.',menuTitle:'Speisekarte',uncategorized:'Sonstiges',selectedProductsCount:'{count} Produkte ausgewählt',close:'Schließen',
}
const ru: Labels = {
  photoImport:'Импорт товаров с фото',photoImportDescription:'Видимые позиции меню извлекаются как редактируемые черновики. До проверки и подтверждения ничего не сохраняется.',choosePhoto:'Выбрать фото меню или товаров',analyzePhoto:'Распознать фото',analyzing:'Фото анализируется...',supportedPhoto:'JPEG, PNG или WebP, не более 8 МБ.',reviewTitle:'Проверка черновиков товаров',reviewDescription:'Проверьте каждое поле. Номер позиции станет SKU только после подтверждения.',include:'Добавить',position:'Позиция / артикул',draftName:'Название товара',draftDescription:'Описание',draftPrice:'Цена',draftCategory:'Категория',validation:'Проверка',noDrafts:'На изображении не найдено достоверных товаров.',nameRequired:'Название обязательно.',invalidPrice:'Введите корректную неотрицательную цену.',duplicateSkuExisting:'Этот SKU уже принадлежит товару: {name}.',duplicateSkuDraft:'Этот SKU повторяется в другом выбранном черновике: {name}.',resolveDuplicate:'Измените SKU или исключите строку перед импортом.',selectedDraftCount:'Выбрано черновиков: {count}',confirmImport:'Импортировать выбранные товары',importing:'Товары импортируются...',imported:'Импортировано товаров: {count}.',importFailed:'Не удалось импортировать товары.',extractionFailed:'Не удалось проанализировать фото. Проверьте изображение и настройки ИИ, затем повторите попытку.',providerMissing:'Настроенный ИИ-провайдер недоступен для анализа изображений.',unsupportedImage:'Используйте корректное изображение JPEG, PNG или WebP.',menuCreate:'Создать меню',menuDescription:'Создайте печатное меню из выбранных товаров Leonety без изменения товарных данных.',selectProductsFirst:'Сначала выберите хотя бы один товар.',template:'Шаблон',templateClassic:'Классический',templateModern:'Современный',templateMinimal:'Минималистичный',templateBold:'Яркий',templateCustom:'Свой образец',customReference:'Загрузить образец шаблона',customReferenceHint:'Leonety использует только цветовое направление. Текст и товары с образца никогда не копируются в меню.',customReferenceFailed:'Не удалось прочитать изображение-образец.',referencePreview:'Изображение-образец',showDescriptions:'Показывать описания',showImages:'Показывать изображения товаров',showArticles:'Показывать артикулы',preview:'Предпросмотр меню',printPdf:'Печать / Сохранить PDF',menuEmpty:'Нет выбранных товаров для меню.',menuTitle:'Меню',uncategorized:'Другое',selectedProductsCount:'Выбрано товаров: {count}',close:'Закрыть',
}
const tr: Labels = {
  photoImport:'Fotoğraftan ürün içe aktar',photoImportDescription:'Görünür menü kalemleri düzenlenebilir taslaklara çıkarılır. İnceleyip onaylamadan hiçbir şey kaydedilmez.',choosePhoto:'Menü veya ürün fotoğrafı seç',analyzePhoto:'Fotoğrafı analiz et',analyzing:'Fotoğraf analiz ediliyor...',supportedPhoto:'JPEG, PNG veya WebP, en fazla 8 MB.',reviewTitle:'Ürün taslaklarını incele',reviewDescription:'Her alanı kontrol edin. Basılı konum yalnızca onaydan sonra SKU olarak eşlenir.',include:'Dahil et',position:'Konum / ürün kodu',draftName:'Ürün adı',draftDescription:'Açıklama',draftPrice:'Fiyat',draftCategory:'Kategori',validation:'Doğrulama',noDrafts:'Bu görselde güvenilir ürün bulunamadı.',nameRequired:'Ad zorunludur.',invalidPrice:'Geçerli, negatif olmayan bir fiyat girin.',duplicateSkuExisting:'Bu SKU zaten şu ürüne ait: {name}.',duplicateSkuDraft:'Bu SKU başka bir seçili taslakta tekrar ediyor: {name}.',resolveDuplicate:'İçe aktarmadan önce SKU’yu düzenleyin veya satırı hariç tutun.',selectedDraftCount:'{count} taslak seçildi',confirmImport:'Seçili ürünleri içe aktar',importing:'Ürünler içe aktarılıyor...',imported:'{count} ürün içe aktarıldı.',importFailed:'Ürünler içe aktarılamadı.',extractionFailed:'Fotoğraf analiz edilemedi. Görseli ve AI yapılandırmasını kontrol edip tekrar deneyin.',providerMissing:'Yapılandırılmış AI sağlayıcısı görsel analizi için kullanılamıyor.',unsupportedImage:'Geçerli bir JPEG, PNG veya WebP görseli kullanın.',menuCreate:'Menü oluştur',menuDescription:'Ürün kayıtlarını değiştirmeden seçili Leonety ürünlerinden yazdırılabilir menü oluşturun.',selectProductsFirst:'Önce en az bir ürün seçin.',template:'Şablon',templateClassic:'Klasik',templateModern:'Modern',templateMinimal:'Minimal',templateBold:'Cesur',templateCustom:'Özel referans',customReference:'Şablon referansı yükle',customReferenceHint:'Leonety yalnızca renk yönünü türetir. Referanstaki metin ve ürünler menüye kopyalanmaz.',customReferenceFailed:'Referans görsel okunamadı.',referencePreview:'Referans görsel',showDescriptions:'Açıklamaları göster',showImages:'Ürün görsellerini göster',showArticles:'Ürün kodlarını göster',preview:'Menü önizlemesi',printPdf:'Yazdır / PDF olarak kaydet',menuEmpty:'Menü için seçili ürün yok.',menuTitle:'Menü',uncategorized:'Diğer',selectedProductsCount:'{count} ürün seçildi',close:'Kapat',
}
const uk: Labels = {
  photoImport:'Імпорт товарів із фото',photoImportDescription:'Видимі позиції меню витягуються як редаговані чернетки. До перевірки й підтвердження нічого не зберігається.',choosePhoto:'Вибрати фото меню або товарів',analyzePhoto:'Проаналізувати фото',analyzing:'Фото аналізується...',supportedPhoto:'JPEG, PNG або WebP, не більше 8 МБ.',reviewTitle:'Перевірка чернеток товарів',reviewDescription:'Перевірте кожне поле. Номер позиції стане SKU лише після підтвердження.',include:'Додати',position:'Позиція / артикул',draftName:'Назва товару',draftDescription:'Опис',draftPrice:'Ціна',draftCategory:'Категорія',validation:'Перевірка',noDrafts:'На зображенні не знайдено достовірних товарів.',nameRequired:'Назва обов’язкова.',invalidPrice:'Введіть коректну невід’ємну ціну.',duplicateSkuExisting:'Цей SKU вже належить товару: {name}.',duplicateSkuDraft:'Цей SKU повторюється в іншій вибраній чернетці: {name}.',resolveDuplicate:'Змініть SKU або виключіть рядок перед імпортом.',selectedDraftCount:'Вибрано чернеток: {count}',confirmImport:'Імпортувати вибрані товари',importing:'Товари імпортуються...',imported:'Імпортовано товарів: {count}.',importFailed:'Не вдалося імпортувати товари.',extractionFailed:'Не вдалося проаналізувати фото. Перевірте зображення та налаштування ШІ й повторіть спробу.',providerMissing:'Налаштований ШІ-провайдер недоступний для аналізу зображень.',unsupportedImage:'Використайте коректне зображення JPEG, PNG або WebP.',menuCreate:'Створити меню',menuDescription:'Створіть меню для друку з вибраних товарів Leonety без зміни товарних даних.',selectProductsFirst:'Спочатку виберіть хоча б один товар.',template:'Шаблон',templateClassic:'Класичний',templateModern:'Сучасний',templateMinimal:'Мінімалістичний',templateBold:'Яскравий',templateCustom:'Власний зразок',customReference:'Завантажити зразок шаблону',customReferenceHint:'Leonety використовує лише колірний напрям. Текст і товари зі зразка ніколи не копіюються в меню.',customReferenceFailed:'Не вдалося прочитати зображення-зразок.',referencePreview:'Зображення-зразок',showDescriptions:'Показувати описи',showImages:'Показувати зображення товарів',showArticles:'Показувати артикули',preview:'Попередній перегляд меню',printPdf:'Друк / Зберегти PDF',menuEmpty:'Немає вибраних товарів для меню.',menuTitle:'Меню',uncategorized:'Інше',selectedProductsCount:'Вибрано товарів: {count}',close:'Закрити',
}
const pl: Labels = {
  photoImport:'Importuj produkty ze zdjęcia',photoImportDescription:'Widoczne pozycje menu są wyodrębniane jako edytowalne wersje robocze. Nic nie zostanie zapisane przed sprawdzeniem i potwierdzeniem.',choosePhoto:'Wybierz zdjęcie menu lub produktów',analyzePhoto:'Analizuj zdjęcie',analyzing:'Analizowanie zdjęcia...',supportedPhoto:'JPEG, PNG lub WebP, maksymalnie 8 MB.',reviewTitle:'Sprawdź wersje robocze produktów',reviewDescription:'Sprawdź każde pole. Wydrukowana pozycja zostanie przypisana do SKU dopiero po potwierdzeniu.',include:'Uwzględnij',position:'Pozycja / artykuł',draftName:'Nazwa produktu',draftDescription:'Opis',draftPrice:'Cena',draftCategory:'Kategoria',validation:'Walidacja',noDrafts:'Na tym obrazie nie znaleziono wiarygodnych produktów.',nameRequired:'Nazwa jest wymagana.',invalidPrice:'Wpisz prawidłową nieujemną cenę.',duplicateSkuExisting:'Ten SKU należy już do produktu: {name}.',duplicateSkuDraft:'Ten SKU powtarza się w innej wybranej wersji roboczej: {name}.',resolveDuplicate:'Edytuj SKU lub wyklucz ten wiersz przed importem.',selectedDraftCount:'Wybrano wersje robocze: {count}',confirmImport:'Importuj wybrane produkty',importing:'Importowanie produktów...',imported:'Zaimportowano produktów: {count}.',importFailed:'Nie udało się zaimportować produktów.',extractionFailed:'Nie udało się przeanalizować zdjęcia. Sprawdź obraz i konfigurację AI, a następnie spróbuj ponownie.',providerMissing:'Skonfigurowany dostawca AI nie jest dostępny do analizy obrazów.',unsupportedImage:'Użyj prawidłowego obrazu JPEG, PNG lub WebP.',menuCreate:'Utwórz menu',menuDescription:'Utwórz menu do druku z wybranych produktów Leonety bez zmiany ich danych.',selectProductsFirst:'Najpierw wybierz co najmniej jeden produkt.',template:'Szablon',templateClassic:'Klasyczny',templateModern:'Nowoczesny',templateMinimal:'Minimalistyczny',templateBold:'Wyrazisty',templateCustom:'Własny wzór',customReference:'Prześlij wzór szablonu',customReferenceHint:'Leonety pobiera tylko kierunek kolorystyczny. Tekst i produkty z obrazu wzorcowego nie są kopiowane do menu.',customReferenceFailed:'Nie udało się odczytać obrazu wzorcowego.',referencePreview:'Obraz wzorcowy',showDescriptions:'Pokaż opisy',showImages:'Pokaż zdjęcia produktów',showArticles:'Pokaż numery artykułów',preview:'Podgląd menu',printPdf:'Drukuj / Zapisz jako PDF',menuEmpty:'Brak wybranych produktów do menu.',menuTitle:'Menu',uncategorized:'Inne',selectedProductsCount:'Wybrano produktów: {count}',close:'Zamknij',
}
const fr: Labels = {
  photoImport:'Importer des produits depuis une photo',photoImportDescription:'Les éléments visibles du menu sont extraits sous forme de brouillons modifiables. Rien n’est enregistré avant vérification et confirmation.',choosePhoto:'Choisir une photo de menu ou de produits',analyzePhoto:'Analyser la photo',analyzing:'Analyse de la photo...',supportedPhoto:'JPEG, PNG ou WebP, 8 Mo maximum.',reviewTitle:'Vérifier les brouillons de produits',reviewDescription:'Vérifiez chaque champ. Une position imprimée n’est associée au SKU qu’après confirmation.',include:'Inclure',position:'Position / article',draftName:'Nom du produit',draftDescription:'Description',draftPrice:'Prix',draftCategory:'Catégorie',validation:'Validation',noDrafts:'Aucun produit fiable n’a été trouvé dans cette image.',nameRequired:'Le nom est obligatoire.',invalidPrice:'Saisissez un prix valide et positif ou nul.',duplicateSkuExisting:'Ce SKU appartient déjà au produit : {name}.',duplicateSkuDraft:'Ce SKU est répété dans un autre brouillon sélectionné : {name}.',resolveDuplicate:'Modifiez le SKU ou excluez cette ligne avant l’import.',selectedDraftCount:'{count} brouillons sélectionnés',confirmImport:'Importer les produits sélectionnés',importing:'Importation des produits...',imported:'{count} produits importés.',importFailed:'Impossible d’importer les produits.',extractionFailed:'Impossible d’analyser la photo. Vérifiez l’image et la configuration de l’IA, puis réessayez.',providerMissing:'Le fournisseur d’IA configuré n’est pas disponible pour l’analyse d’images.',unsupportedImage:'Utilisez une image JPEG, PNG ou WebP valide.',menuCreate:'Créer un menu',menuDescription:'Créez un menu imprimable avec les produits Leonety sélectionnés sans modifier leurs données.',selectProductsFirst:'Sélectionnez d’abord au moins un produit.',template:'Modèle',templateClassic:'Classique',templateModern:'Moderne',templateMinimal:'Minimaliste',templateBold:'Audacieux',templateCustom:'Référence personnalisée',customReference:'Téléverser une référence de modèle',customReferenceHint:'Leonety extrait uniquement une orientation de couleurs. Les textes et produits de l’image de référence ne sont jamais copiés dans le menu.',customReferenceFailed:'Impossible de lire l’image de référence.',referencePreview:'Image de référence',showDescriptions:'Afficher les descriptions',showImages:'Afficher les images des produits',showArticles:'Afficher les références',preview:'Aperçu du menu',printPdf:'Imprimer / Enregistrer en PDF',menuEmpty:'Aucun produit sélectionné n’est disponible pour le menu.',menuTitle:'Menu',uncategorized:'Autres',selectedProductsCount:'{count} produits sélectionnés',close:'Fermer',
}

function prefix(dictionary: Labels) {
  return Object.fromEntries(Object.entries(dictionary).map(([key, value]) => [`productMenu.${key}`, value]))
}

export const productMenuDictionaries: Record<Locale, Record<string, string>> = {
  en: prefix(en), de: prefix(de), ru: prefix(ru), tr: prefix(tr), uk: prefix(uk), pl: prefix(pl), fr: prefix(fr),
}
